/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as GuestLoginRouteImport } from './routes/_guest/login'
import { Route as AuthedTransactionsIndexRouteImport } from './routes/_authed/transactions/index'
import { Route as AuthedSnapshotsIndexRouteImport } from './routes/_authed/snapshots/index'
import { Route as AuthedLocationsIndexRouteImport } from './routes/_authed/locations/index'
import { Route as AuthedItemsIndexRouteImport } from './routes/_authed/items/index'
import { Route as AuthedItemCategoriesIndexRouteImport } from './routes/_authed/item-categories/index'
import { Route as AuthedInventoriesIndexRouteImport } from './routes/_authed/inventories/index'
import { Route as AuthedTransactionsIdRouteImport } from './routes/_authed/transactions/$id'
import { Route as AuthedSnapshotsIdRouteImport } from './routes/_authed/snapshots/$id'
import { Route as AuthedLocationsIdRouteImport } from './routes/_authed/locations/$id'
import { Route as AuthedItemsIdRouteImport } from './routes/_authed/items/$id'
import { Route as AuthedItemCategoriesIdRouteImport } from './routes/_authed/item-categories/$id'
import { Route as AuthedInventoriesIdRouteImport } from './routes/_authed/inventories/$id'

const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const AuthedTransactionsIndexRoute = AuthedTransactionsIndexRouteImport.update({
  id: '/transactions/',
  path: '/transactions/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSnapshotsIndexRoute = AuthedSnapshotsIndexRouteImport.update({
  id: '/snapshots/',
  path: '/snapshots/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLocationsIndexRoute = AuthedLocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedItemsIndexRoute = AuthedItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedItemCategoriesIndexRoute =
  AuthedItemCategoriesIndexRouteImport.update({
    id: '/item-categories/',
    path: '/item-categories/',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedInventoriesIndexRoute = AuthedInventoriesIndexRouteImport.update({
  id: '/inventories/',
  path: '/inventories/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTransactionsIdRoute = AuthedTransactionsIdRouteImport.update({
  id: '/transactions/$id',
  path: '/transactions/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSnapshotsIdRoute = AuthedSnapshotsIdRouteImport.update({
  id: '/snapshots/$id',
  path: '/snapshots/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedLocationsIdRoute = AuthedLocationsIdRouteImport.update({
  id: '/locations/$id',
  path: '/locations/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedItemsIdRoute = AuthedItemsIdRouteImport.update({
  id: '/items/$id',
  path: '/items/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedItemCategoriesIdRoute = AuthedItemCategoriesIdRouteImport.update({
  id: '/item-categories/$id',
  path: '/item-categories/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInventoriesIdRoute = AuthedInventoriesIdRouteImport.update({
  id: '/inventories/$id',
  path: '/inventories/$id',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof GuestLoginRoute
  '/inventories/$id': typeof AuthedInventoriesIdRoute
  '/item-categories/$id': typeof AuthedItemCategoriesIdRoute
  '/items/$id': typeof AuthedItemsIdRoute
  '/locations/$id': typeof AuthedLocationsIdRoute
  '/snapshots/$id': typeof AuthedSnapshotsIdRoute
  '/transactions/$id': typeof AuthedTransactionsIdRoute
  '/inventories/': typeof AuthedInventoriesIndexRoute
  '/item-categories/': typeof AuthedItemCategoriesIndexRoute
  '/items/': typeof AuthedItemsIndexRoute
  '/locations/': typeof AuthedLocationsIndexRoute
  '/snapshots/': typeof AuthedSnapshotsIndexRoute
  '/transactions/': typeof AuthedTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedIndexRoute
  '/login': typeof GuestLoginRoute
  '/inventories/$id': typeof AuthedInventoriesIdRoute
  '/item-categories/$id': typeof AuthedItemCategoriesIdRoute
  '/items/$id': typeof AuthedItemsIdRoute
  '/locations/$id': typeof AuthedLocationsIdRoute
  '/snapshots/$id': typeof AuthedSnapshotsIdRoute
  '/transactions/$id': typeof AuthedTransactionsIdRoute
  '/inventories': typeof AuthedInventoriesIndexRoute
  '/item-categories': typeof AuthedItemCategoriesIndexRoute
  '/items': typeof AuthedItemsIndexRoute
  '/locations': typeof AuthedLocationsIndexRoute
  '/snapshots': typeof AuthedSnapshotsIndexRoute
  '/transactions': typeof AuthedTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/inventories/$id': typeof AuthedInventoriesIdRoute
  '/_authed/item-categories/$id': typeof AuthedItemCategoriesIdRoute
  '/_authed/items/$id': typeof AuthedItemsIdRoute
  '/_authed/locations/$id': typeof AuthedLocationsIdRoute
  '/_authed/snapshots/$id': typeof AuthedSnapshotsIdRoute
  '/_authed/transactions/$id': typeof AuthedTransactionsIdRoute
  '/_authed/inventories/': typeof AuthedInventoriesIndexRoute
  '/_authed/item-categories/': typeof AuthedItemCategoriesIndexRoute
  '/_authed/items/': typeof AuthedItemsIndexRoute
  '/_authed/locations/': typeof AuthedLocationsIndexRoute
  '/_authed/snapshots/': typeof AuthedSnapshotsIndexRoute
  '/_authed/transactions/': typeof AuthedTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/inventories/$id'
    | '/item-categories/$id'
    | '/items/$id'
    | '/locations/$id'
    | '/snapshots/$id'
    | '/transactions/$id'
    | '/inventories/'
    | '/item-categories/'
    | '/items/'
    | '/locations/'
    | '/snapshots/'
    | '/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/inventories/$id'
    | '/item-categories/$id'
    | '/items/$id'
    | '/locations/$id'
    | '/snapshots/$id'
    | '/transactions/$id'
    | '/inventories'
    | '/item-categories'
    | '/items'
    | '/locations'
    | '/snapshots'
    | '/transactions'
  id:
    | '__root__'
    | '/_authed'
    | '/_guest'
    | '/_guest/login'
    | '/_authed/'
    | '/_authed/inventories/$id'
    | '/_authed/item-categories/$id'
    | '/_authed/items/$id'
    | '/_authed/locations/$id'
    | '/_authed/snapshots/$id'
    | '/_authed/transactions/$id'
    | '/_authed/inventories/'
    | '/_authed/item-categories/'
    | '/_authed/items/'
    | '/_authed/locations/'
    | '/_authed/snapshots/'
    | '/_authed/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_authed/transactions/': {
      id: '/_authed/transactions/'
      path: '/transactions'
      fullPath: '/transactions/'
      preLoaderRoute: typeof AuthedTransactionsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/snapshots/': {
      id: '/_authed/snapshots/'
      path: '/snapshots'
      fullPath: '/snapshots/'
      preLoaderRoute: typeof AuthedSnapshotsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/locations/': {
      id: '/_authed/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof AuthedLocationsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/items/': {
      id: '/_authed/items/'
      path: '/items'
      fullPath: '/items/'
      preLoaderRoute: typeof AuthedItemsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/item-categories/': {
      id: '/_authed/item-categories/'
      path: '/item-categories'
      fullPath: '/item-categories/'
      preLoaderRoute: typeof AuthedItemCategoriesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inventories/': {
      id: '/_authed/inventories/'
      path: '/inventories'
      fullPath: '/inventories/'
      preLoaderRoute: typeof AuthedInventoriesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/transactions/$id': {
      id: '/_authed/transactions/$id'
      path: '/transactions/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof AuthedTransactionsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/snapshots/$id': {
      id: '/_authed/snapshots/$id'
      path: '/snapshots/$id'
      fullPath: '/snapshots/$id'
      preLoaderRoute: typeof AuthedSnapshotsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/locations/$id': {
      id: '/_authed/locations/$id'
      path: '/locations/$id'
      fullPath: '/locations/$id'
      preLoaderRoute: typeof AuthedLocationsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/items/$id': {
      id: '/_authed/items/$id'
      path: '/items/$id'
      fullPath: '/items/$id'
      preLoaderRoute: typeof AuthedItemsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/item-categories/$id': {
      id: '/_authed/item-categories/$id'
      path: '/item-categories/$id'
      fullPath: '/item-categories/$id'
      preLoaderRoute: typeof AuthedItemCategoriesIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/inventories/$id': {
      id: '/_authed/inventories/$id'
      path: '/inventories/$id'
      fullPath: '/inventories/$id'
      preLoaderRoute: typeof AuthedInventoriesIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedInventoriesIdRoute: typeof AuthedInventoriesIdRoute
  AuthedItemCategoriesIdRoute: typeof AuthedItemCategoriesIdRoute
  AuthedItemsIdRoute: typeof AuthedItemsIdRoute
  AuthedLocationsIdRoute: typeof AuthedLocationsIdRoute
  AuthedSnapshotsIdRoute: typeof AuthedSnapshotsIdRoute
  AuthedTransactionsIdRoute: typeof AuthedTransactionsIdRoute
  AuthedInventoriesIndexRoute: typeof AuthedInventoriesIndexRoute
  AuthedItemCategoriesIndexRoute: typeof AuthedItemCategoriesIndexRoute
  AuthedItemsIndexRoute: typeof AuthedItemsIndexRoute
  AuthedLocationsIndexRoute: typeof AuthedLocationsIndexRoute
  AuthedSnapshotsIndexRoute: typeof AuthedSnapshotsIndexRoute
  AuthedTransactionsIndexRoute: typeof AuthedTransactionsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedInventoriesIdRoute: AuthedInventoriesIdRoute,
  AuthedItemCategoriesIdRoute: AuthedItemCategoriesIdRoute,
  AuthedItemsIdRoute: AuthedItemsIdRoute,
  AuthedLocationsIdRoute: AuthedLocationsIdRoute,
  AuthedSnapshotsIdRoute: AuthedSnapshotsIdRoute,
  AuthedTransactionsIdRoute: AuthedTransactionsIdRoute,
  AuthedInventoriesIndexRoute: AuthedInventoriesIndexRoute,
  AuthedItemCategoriesIndexRoute: AuthedItemCategoriesIndexRoute,
  AuthedItemsIndexRoute: AuthedItemsIndexRoute,
  AuthedLocationsIndexRoute: AuthedLocationsIndexRoute,
  AuthedSnapshotsIndexRoute: AuthedSnapshotsIndexRoute,
  AuthedTransactionsIndexRoute: AuthedTransactionsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
